//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeTracker.Presentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackItemModel
    {
        public System.Guid Id { get; set; }
        public decimal BuyLegalCount { get; set; }
        public decimal BuyLegalVolume { get; set; }
        public decimal BuyRealCount { get; set; }
        public decimal BuyRealVolume { get; set; }
        public decimal FinalPrice { get; set; }
        public decimal LastTransactionPrice { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public decimal SellLegalCount { get; set; }
        public decimal SellLegalVolume { get; set; }
        public decimal SellRealCount { get; set; }
        public decimal SellRealVolume { get; set; }
        public string StockId { get; set; }
        public decimal TransactionCount { get; set; }
        public decimal TransactionValue { get; set; }
        public decimal TransactionVolume { get; set; }
        public System.DateTime LastTransactionDateTime { get; set; }
    }
}
